runtime: nodejs14

env_variables:
  CLOUD_SQL_USERNAME: test
  CLOUD_SQL_PASSWORD: 1234
  CLOUD_SQL_DATABASE_NAME: pitchfork
  CLOUD_SQL_CONNECTION_NAME: elite-rider-300405:asia-southeast1:stadvdv-mco1-pitchfork

beta_settings:
  cloud_sql_instances: elite-rider-300405:asia-southeast1:stadvdv-mco1-pitchfork